[package]
name = "io-uring-experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.4.4"
io-uring = "0.5.2"
libc = "0.2.119"